---
deployment:
  tasks:
    - export DEPLOYPATH=/home/craftmd/public_html
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R .next $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp next.config.js $DEPLOYPATH